name: Generate Ascii Art
on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mscoutermarsh/ascii-art-action@master
          with:
          text: 'LGTM'

